[tool.poetry]
name = "tronpy"
version = "0.2.4"
description = "TRON Python client library"
authors = ["andelf <andelf@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/andelf/tronpy"
repository = "https://github.com/andelf/tronpy"
keywords = ["tron", "api", "blockchain"]
classifiers = [
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  'Natural Language :: English',
]

[tool.poetry.dependencies]
python = "^3.6"
ecdsa = "^0.15"
requests = "^2.23.0"
base58 = "^2.0.0"
pycryptodome = "^3.9.7"
eth_abi = "^0.5.0"  # for compatibility with web3==3.16.5
httpx = "^0.16.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.9.0"
flake8 = "^3.8.2"
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.780"
sphinx = "^3.1.1"
pytest-asyncio = "^0.14.0"

[tool.black]
line-length = 100
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[build-system]
requires = ["poetry >= 0.12, <1"]
build-backend = "poetry.masonry.api"
